// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/delivery.dart';
import 'api/logger.dart';
import 'api/media.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LogLevelPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  LogLevel
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
    dynamic raw,
  );

  @protected
  LogLevel
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
    dynamic raw,
  );

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Dco(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  CompressParams dco_decode_box_autoadd_compress_params(dynamic raw);

  @protected
  ImageThumbnailParams dco_decode_box_autoadd_image_thumbnail_params(
    dynamic raw,
  );

  @protected
  OutputFormat dco_decode_box_autoadd_output_format(dynamic raw);

  @protected
  (int, int) dco_decode_box_autoadd_record_u_32_u_32(dynamic raw);

  @protected
  ThumbnailSizeType dco_decode_box_autoadd_thumbnail_size_type(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  VideoThumbnailParams dco_decode_box_autoadd_video_thumbnail_params(
    dynamic raw,
  );

  @protected
  WriteToFiles dco_decode_box_autoadd_write_to_files(dynamic raw);

  @protected
  CompressParams dco_decode_compress_params(dynamic raw);

  @protected
  CompressionEstimate dco_decode_compression_estimate(dynamic raw);

  @protected
  DeliveryEstimate dco_decode_delivery_estimate(dynamic raw);

  @protected
  DeliveryProfileId dco_decode_delivery_profile_id(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ImageThumbnailParams dco_decode_image_thumbnail_params(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ResolutionPreset> dco_decode_list_resolution_preset(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  ImageThumbnailParams? dco_decode_opt_box_autoadd_image_thumbnail_params(
    dynamic raw,
  );

  @protected
  OutputFormat? dco_decode_opt_box_autoadd_output_format(dynamic raw);

  @protected
  ThumbnailSizeType? dco_decode_opt_box_autoadd_thumbnail_size_type(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  WriteToFiles? dco_decode_opt_box_autoadd_write_to_files(dynamic raw);

  @protected
  OutputFormat dco_decode_output_format(dynamic raw);

  @protected
  (int, int) dco_decode_record_u_32_u_32(dynamic raw);

  @protected
  ResolutionPreset dco_decode_resolution_preset(dynamic raw);

  @protected
  ThumbnailSizeType dco_decode_thumbnail_size_type(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VideoDeliveryEstimates dco_decode_video_delivery_estimates(dynamic raw);

  @protected
  VideoInfo dco_decode_video_info(dynamic raw);

  @protected
  VideoThumbnailParams dco_decode_video_thumbnail_params(dynamic raw);

  @protected
  WriteToFiles dco_decode_write_to_files(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  LogLevel
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
    SseDeserializer deserializer,
  );

  @protected
  LogLevel
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Dco(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CompressParams sse_decode_box_autoadd_compress_params(
    SseDeserializer deserializer,
  );

  @protected
  ImageThumbnailParams sse_decode_box_autoadd_image_thumbnail_params(
    SseDeserializer deserializer,
  );

  @protected
  OutputFormat sse_decode_box_autoadd_output_format(
    SseDeserializer deserializer,
  );

  @protected
  (int, int) sse_decode_box_autoadd_record_u_32_u_32(
    SseDeserializer deserializer,
  );

  @protected
  ThumbnailSizeType sse_decode_box_autoadd_thumbnail_size_type(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  VideoThumbnailParams sse_decode_box_autoadd_video_thumbnail_params(
    SseDeserializer deserializer,
  );

  @protected
  WriteToFiles sse_decode_box_autoadd_write_to_files(
    SseDeserializer deserializer,
  );

  @protected
  CompressParams sse_decode_compress_params(SseDeserializer deserializer);

  @protected
  CompressionEstimate sse_decode_compression_estimate(
    SseDeserializer deserializer,
  );

  @protected
  DeliveryEstimate sse_decode_delivery_estimate(SseDeserializer deserializer);

  @protected
  DeliveryProfileId sse_decode_delivery_profile_id(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ImageThumbnailParams sse_decode_image_thumbnail_params(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ResolutionPreset> sse_decode_list_resolution_preset(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ImageThumbnailParams? sse_decode_opt_box_autoadd_image_thumbnail_params(
    SseDeserializer deserializer,
  );

  @protected
  OutputFormat? sse_decode_opt_box_autoadd_output_format(
    SseDeserializer deserializer,
  );

  @protected
  ThumbnailSizeType? sse_decode_opt_box_autoadd_thumbnail_size_type(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  WriteToFiles? sse_decode_opt_box_autoadd_write_to_files(
    SseDeserializer deserializer,
  );

  @protected
  OutputFormat sse_decode_output_format(SseDeserializer deserializer);

  @protected
  (int, int) sse_decode_record_u_32_u_32(SseDeserializer deserializer);

  @protected
  ResolutionPreset sse_decode_resolution_preset(SseDeserializer deserializer);

  @protected
  ThumbnailSizeType sse_decode_thumbnail_size_type(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VideoDeliveryEstimates sse_decode_video_delivery_estimates(
    SseDeserializer deserializer,
  );

  @protected
  VideoInfo sse_decode_video_info(SseDeserializer deserializer);

  @protected
  VideoThumbnailParams sse_decode_video_thumbnail_params(
    SseDeserializer deserializer,
  );

  @protected
  WriteToFiles sse_decode_write_to_files(SseDeserializer deserializer);

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String cst_encode_StreamSink_String_Dco(RustStreamSink<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  bool cst_encode_box_autoadd_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_bool(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_compress_params(CompressParams raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_compress_params(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_image_thumbnail_params(
    ImageThumbnailParams raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_image_thumbnail_params(raw);
  }

  @protected
  int cst_encode_box_autoadd_output_format(OutputFormat raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_output_format(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_record_u_32_u_32((int, int) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_record_u_32_u_32(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_thumbnail_size_type(ThumbnailSizeType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_thumbnail_size_type(raw);
  }

  @protected
  int cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_32(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_64(raw);
  }

  @protected
  int cst_encode_box_autoadd_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_8(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_video_thumbnail_params(
    VideoThumbnailParams raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_video_thumbnail_params(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_write_to_files(WriteToFiles raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_write_to_files(raw);
  }

  @protected
  JSAny cst_encode_compress_params(CompressParams raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_32(raw.targetBitrateKbps),
      cst_encode_opt_String(raw.preset),
      cst_encode_opt_box_autoadd_u_8(raw.crf),
      cst_encode_opt_box_autoadd_u_32(raw.width),
      cst_encode_opt_box_autoadd_u_32(raw.height),
      cst_encode_opt_box_autoadd_u_64(raw.sampleDurationMs),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_compression_estimate(CompressionEstimate raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_64(raw.estimatedSizeBytes),
      cst_encode_u_64(raw.estimatedDurationMs),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_delivery_estimate(DeliveryEstimate raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_delivery_profile_id(raw.profileId),
      cst_encode_u_32(raw.width),
      cst_encode_u_32(raw.height),
      cst_encode_u_64(raw.estimatedSizeBytes),
      cst_encode_u_32(raw.videoBitrateKbps),
      cst_encode_u_32(raw.audioBitrateKbps),
      cst_encode_u_64(raw.estimatedEncodeTimeMs),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_image_thumbnail_params(ImageThumbnailParams raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_box_autoadd_thumbnail_size_type(raw.sizeType),
      cst_encode_opt_box_autoadd_output_format(raw.format),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_resolution_preset(List<ResolutionPreset> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_resolution_preset).toList().jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  bool? cst_encode_opt_box_autoadd_bool(bool? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_bool(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_image_thumbnail_params(
    ImageThumbnailParams? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? null
        : cst_encode_box_autoadd_image_thumbnail_params(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_output_format(OutputFormat? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_output_format(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_thumbnail_size_type(
    ThumbnailSizeType? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_thumbnail_size_type(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_u_64(BigInt? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_64(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_u_8(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_8(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_write_to_files(WriteToFiles? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_write_to_files(raw);
  }

  @protected
  JSAny cst_encode_record_u_32_u_32((int, int) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_u_32(raw.$1), cst_encode_u_32(raw.$2)].jsify()!;
  }

  @protected
  JSAny cst_encode_resolution_preset(ResolutionPreset raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.name),
      cst_encode_u_32(raw.width),
      cst_encode_u_32(raw.height),
      cst_encode_u_64(raw.bitrate),
      cst_encode_u_8(raw.crf),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_thumbnail_size_type(ThumbnailSizeType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    if (raw is ThumbnailSizeType_Icon) {
      return [0].jsify()!;
    }
    if (raw is ThumbnailSizeType_Small) {
      return [1].jsify()!;
    }
    if (raw is ThumbnailSizeType_Medium) {
      return [2].jsify()!;
    }
    if (raw is ThumbnailSizeType_Large) {
      return [3].jsify()!;
    }
    if (raw is ThumbnailSizeType_Larger) {
      return [4].jsify()!;
    }
    if (raw is ThumbnailSizeType_Custom) {
      return [5, cst_encode_box_autoadd_record_u_32_u_32(raw.field0)].jsify()!;
    }

    throw Exception('unreachable');
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_video_delivery_estimates(VideoDeliveryEstimates raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_delivery_estimate(raw.hd720),
      cst_encode_delivery_estimate(raw.sd480),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_video_info(VideoInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_64(raw.durationMs),
      cst_encode_u_32(raw.width),
      cst_encode_u_32(raw.height),
      cst_encode_i_32(raw.rotationDegrees),
      cst_encode_u_64(raw.sizeBytes),
      cst_encode_opt_box_autoadd_u_64(raw.bitrate),
      cst_encode_opt_String(raw.codecName),
      cst_encode_opt_String(raw.formatName),
      cst_encode_list_resolution_preset(raw.suggestions),
      cst_encode_video_delivery_estimates(raw.delivery),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_video_thumbnail_params(VideoThumbnailParams raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_64(raw.timeMs),
      cst_encode_opt_box_autoadd_thumbnail_size_type(raw.sizeType),
      cst_encode_opt_box_autoadd_output_format(raw.format),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_write_to_files(WriteToFiles raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.path),
      cst_encode_String(raw.filePrefix),
      cst_encode_opt_String(raw.fileSuffix),
      cst_encode_opt_box_autoadd_u_64(raw.maxFiles),
    ].jsify()!;
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
    LogLevel raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
    LogLevel raw,
  );

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_delivery_profile_id(DeliveryProfileId raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_output_format(OutputFormat raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
    LogLevel self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
    LogLevel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_String_Dco(
    RustStreamSink<String> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_compress_params(
    CompressParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_image_thumbnail_params(
    ImageThumbnailParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_output_format(
    OutputFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_u_32_u_32(
    (int, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_thumbnail_size_type(
    ThumbnailSizeType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_video_thumbnail_params(
    VideoThumbnailParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_write_to_files(
    WriteToFiles self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_compress_params(
    CompressParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_compression_estimate(
    CompressionEstimate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delivery_estimate(
    DeliveryEstimate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_delivery_profile_id(
    DeliveryProfileId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_image_thumbnail_params(
    ImageThumbnailParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_resolution_preset(
    List<ResolutionPreset> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_image_thumbnail_params(
    ImageThumbnailParams? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_output_format(
    OutputFormat? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_thumbnail_size_type(
    ThumbnailSizeType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_write_to_files(
    WriteToFiles? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_output_format(OutputFormat self, SseSerializer serializer);

  @protected
  void sse_encode_record_u_32_u_32((int, int) self, SseSerializer serializer);

  @protected
  void sse_encode_resolution_preset(
    ResolutionPreset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_thumbnail_size_type(
    ThumbnailSizeType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_video_delivery_estimates(
    VideoDeliveryEstimates self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_video_info(VideoInfo self, SseSerializer serializer);

  @protected
  void sse_encode_video_thumbnail_params(
    VideoThumbnailParams self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_write_to_files(WriteToFiles self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__media__compress_video(
    NativePortType port_,
    String path,
    String output_path,
    JSAny params,
  ) => wasmModule.wire__crate__api__media__compress_video(
    port_,
    path,
    output_path,
    params,
  );

  void wire__crate__api__logger__debug_threads(NativePortType port_) =>
      wasmModule.wire__crate__api__logger__debug_threads(port_);

  void wire__crate__api__media__estimate_compression(
    NativePortType port_,
    String path,
    String temp_output_path,
    JSAny params,
  ) => wasmModule.wire__crate__api__media__estimate_compression(
    port_,
    path,
    temp_output_path,
    params,
  );

  void wire__crate__api__media__generate_image_thumbnail(
    NativePortType port_,
    String path,
    String output_path,
    JSAny? params,
    String? suffix,
  ) => wasmModule.wire__crate__api__media__generate_image_thumbnail(
    port_,
    path,
    output_path,
    params,
    suffix,
  );

  void wire__crate__api__media__generate_video_thumbnail(
    NativePortType port_,
    String path,
    String output_path,
    JSAny params,
    bool? empty_image_fallback,
  ) => wasmModule.wire__crate__api__media__generate_video_thumbnail(
    port_,
    path,
    output_path,
    params,
    empty_image_fallback,
  );

  void wire__crate__api__media__generate_video_timeline_thumbnails(
    NativePortType port_,
    String path,
    String output_path,
    JSAny? params,
    int num_thumbnails,
    bool? empty_image_fallback,
    String sink,
  ) => wasmModule.wire__crate__api__media__generate_video_timeline_thumbnails(
    port_,
    path,
    output_path,
    params,
    num_thumbnails,
    empty_image_fallback,
    sink,
  );

  void wire__crate__api__media__get_video_delivery_estimates(
    NativePortType port_,
    String path,
  ) => wasmModule.wire__crate__api__media__get_video_delivery_estimates(
    port_,
    path,
  );

  void wire__crate__api__media__get_video_info(
    NativePortType port_,
    String path,
  ) => wasmModule.wire__crate__api__media__get_video_info(port_, path);

  void wire__crate__api__logger__init_logger(
    NativePortType port_,
    int log_level,
    bool write_to_stdout_or_system,
    JSAny? write_to_files,
    bool use_lightweight_tokio_runtime,
  ) => wasmModule.wire__crate__api__logger__init_logger(
    port_,
    log_level,
    write_to_stdout_or_system,
    write_to_files,
    use_lightweight_tokio_runtime,
  );

  void wire__crate__api__logger__log(
    NativePortType port_,
    String file,
    int? line,
    int level,
    String target,
    String message,
  ) => wasmModule.wire__crate__api__logger__log(
    port_,
    file,
    line,
    level,
    target,
    message,
  );

  void wire__crate__api__logger__log_level_for_verbose_backend(
    NativePortType port_,
    bool verbose,
  ) => wasmModule.wire__crate__api__logger__log_level_for_verbose_backend(
    port_,
    verbose,
  );

  void wire__crate__api__media__output_format_extension(
    NativePortType port_,
    int that,
  ) => wasmModule.wire__crate__api__media__output_format_extension(port_, that);

  void wire__crate__api__logger__reload_tracing_file_writer(
    NativePortType port_,
    JSAny write_to_files,
  ) => wasmModule.wire__crate__api__logger__reload_tracing_file_writer(
    port_,
    write_to_files,
  );

  void wire__crate__api__media__thumbnail_size_type_dimensions(
    NativePortType port_,
    JSAny that,
  ) => wasmModule.wire__crate__api__media__thumbnail_size_type_dimensions(
    port_,
    that,
  );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__media__compress_video(
    NativePortType port_,
    String path,
    String output_path,
    JSAny params,
  );

  external void wire__crate__api__logger__debug_threads(NativePortType port_);

  external void wire__crate__api__media__estimate_compression(
    NativePortType port_,
    String path,
    String temp_output_path,
    JSAny params,
  );

  external void wire__crate__api__media__generate_image_thumbnail(
    NativePortType port_,
    String path,
    String output_path,
    JSAny? params,
    String? suffix,
  );

  external void wire__crate__api__media__generate_video_thumbnail(
    NativePortType port_,
    String path,
    String output_path,
    JSAny params,
    bool? empty_image_fallback,
  );

  external void wire__crate__api__media__generate_video_timeline_thumbnails(
    NativePortType port_,
    String path,
    String output_path,
    JSAny? params,
    int num_thumbnails,
    bool? empty_image_fallback,
    String sink,
  );

  external void wire__crate__api__media__get_video_delivery_estimates(
    NativePortType port_,
    String path,
  );

  external void wire__crate__api__media__get_video_info(
    NativePortType port_,
    String path,
  );

  external void wire__crate__api__logger__init_logger(
    NativePortType port_,
    int log_level,
    bool write_to_stdout_or_system,
    JSAny? write_to_files,
    bool use_lightweight_tokio_runtime,
  );

  external void wire__crate__api__logger__log(
    NativePortType port_,
    String file,
    int? line,
    int level,
    String target,
    String message,
  );

  external void wire__crate__api__logger__log_level_for_verbose_backend(
    NativePortType port_,
    bool verbose,
  );

  external void wire__crate__api__media__output_format_extension(
    NativePortType port_,
    int that,
  );

  external void wire__crate__api__logger__reload_tracing_file_writer(
    NativePortType port_,
    JSAny write_to_files,
  );

  external void wire__crate__api__media__thumbnail_size_type_dimensions(
    NativePortType port_,
    JSAny that,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLogLevel(
    int ptr,
  );
}
