import 'dart:io';

import 'package:ffigen/ffigen.dart';

void main() {
  final packageRoot = Platform.script.resolve('../');
  FfiGenerator(
    headers: Headers(
      entryPoints: [packageRoot.resolve('../native/bindings.h')],
    ),
    functions: Functions.includeSet({
      'media_get_video_info',
      'media_generate_thumbnail',
      'media_free_video_info',
      'media_free_buffer',
    }),
    structs: Structs.includeSet({
      'CBuffer',
      'CVideoInfo',
    }),
    output: Output(
      dartFile: packageRoot.resolve('lib/src/bindings/ffi.g.dart'),
      preamble: '''
// This file is automatically generated by ffigen.dart; DO NOT MANUALLY EDIT!

''',
    ),
  ).generate();
}
