// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = DcoCodec,
    default_rust_opaque = RustOpaqueNom,
    default_rust_auto_opaque = RustAutoOpaqueNom,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 793834831;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__probe_video_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    path: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "probe_video",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_path = path.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::probe_video(api_path).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__thumbnail_image_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    path: impl CstDecode<String>,
    time_sec: impl CstDecode<f64>,
    max_edge: impl CstDecode<u32>,
    format: impl CstDecode<crate::api::ThumbnailFormat>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "thumbnail_image",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_path = path.cst_decode();
            let api_time_sec = time_sec.cst_decode();
            let api_max_edge = max_edge.cst_decode();
            let api_format = format.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::thumbnail_image(
                            api_path,
                            api_time_sec,
                            api_max_edge,
                            api_format,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__thumbnail_save_to_path_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    path: impl CstDecode<String>,
    output_path: impl CstDecode<String>,
    time_sec: impl CstDecode<f64>,
    max_edge: impl CstDecode<u32>,
    format: impl CstDecode<crate::api::ThumbnailFormat>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "thumbnail_save_to_path",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_path = path.cst_decode();
            let api_output_path = output_path.cst_decode();
            let api_time_sec = time_sec.cst_decode();
            let api_max_edge = max_edge.cst_decode();
            let api_format = format.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::thumbnail_save_to_path(
                            api_path,
                            api_output_path,
                            api_time_sec,
                            api_max_edge,
                            api_format,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__timeline_thumbnails_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    path: impl CstDecode<String>,
    frame_count: impl CstDecode<u32>,
    max_edge: impl CstDecode<u32>,
    format: impl CstDecode<crate::api::ThumbnailFormat>,
    sink: impl CstDecode<
        StreamSink<crate::api::TimelineThumbnail, flutter_rust_bridge::for_generated::DcoCodec>,
    >,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "timeline_thumbnails",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_path = path.cst_decode();
            let api_frame_count = frame_count.cst_decode();
            let api_max_edge = max_edge.cst_decode();
            let api_format = format.cst_decode();
            let api_sink = sink.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::timeline_thumbnails(
                            api_path,
                            api_frame_count,
                            api_max_edge,
                            api_format,
                            api_sink,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__transcode_video_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    input_path: impl CstDecode<String>,
    output_path: impl CstDecode<String>,
    video_bitrate_kbps: impl CstDecode<u32>,
    max_width: impl CstDecode<u32>,
    audio_bitrate_kbps: impl CstDecode<u32>,
    sink: impl CstDecode<
        StreamSink<crate::api::TranscodeProgress, flutter_rust_bridge::for_generated::DcoCodec>,
    >,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "transcode_video",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_input_path = input_path.cst_decode();
            let api_output_path = output_path.cst_decode();
            let api_video_bitrate_kbps = video_bitrate_kbps.cst_decode();
            let api_max_width = max_width.cst_decode();
            let api_audio_bitrate_kbps = audio_bitrate_kbps.cst_decode();
            let api_sink = sink.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, String>(
                    (move || async move {
                        let output_ok = crate::api::transcode_video(
                            api_input_path,
                            api_output_path,
                            api_video_bitrate_kbps,
                            api_max_width,
                            api_audio_bitrate_kbps,
                            api_sink,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}

// Section: dart2rust

impl CstDecode<f64> for f64 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> f64 {
        self
    }
}
impl CstDecode<i32> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> i32 {
        self
    }
}
impl CstDecode<i64> for i64 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> i64 {
        self
    }
}
impl CstDecode<crate::api::ThumbnailFormat> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::ThumbnailFormat {
        match self {
            0 => crate::api::ThumbnailFormat::Png,
            1 => crate::api::ThumbnailFormat::Jpeg,
            2 => crate::api::ThumbnailFormat::Webp,
            _ => unreachable!("Invalid variant for ThumbnailFormat: {}", self),
        }
    }
}
impl CstDecode<u32> for u32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u32 {
        self
    }
}
impl CstDecode<u8> for u8 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u8 {
        self
    }
}
impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::TimelineThumbnail, flutter_rust_bridge::for_generated::DcoCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::TranscodeProgress, flutter_rust_bridge::for_generated::DcoCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<i64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::ThumbnailFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::ThumbnailFormat::Png,
            1 => crate::api::ThumbnailFormat::Jpeg,
            2 => crate::api::ThumbnailFormat::Webp,
            _ => unreachable!("Invalid variant for ThumbnailFormat: {}", inner),
        };
    }
}

impl SseDecode for crate::api::TimelineThumbnail {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_index = <u32>::sse_decode(deserializer);
        let mut var_timeSec = <f64>::sse_decode(deserializer);
        let mut var_imageBytes = <Vec<u8>>::sse_decode(deserializer);
        return crate::api::TimelineThumbnail {
            index: var_index,
            time_sec: var_timeSec,
            image_bytes: var_imageBytes,
        };
    }
}

impl SseDecode for crate::api::TranscodeProgress {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_phase = <String>::sse_decode(deserializer);
        let mut var_fraction = <f64>::sse_decode(deserializer);
        let mut var_message = <Option<String>>::sse_decode(deserializer);
        return crate::api::TranscodeProgress {
            phase: var_phase,
            fraction: var_fraction,
            message: var_message,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::VideoProbe {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_durationMs = <Option<i64>>::sse_decode(deserializer);
        let mut var_width = <Option<u32>>::sse_decode(deserializer);
        let mut var_height = <Option<u32>>::sse_decode(deserializer);
        let mut var_videoBitrate = <Option<i64>>::sse_decode(deserializer);
        let mut var_audioBitrate = <Option<i64>>::sse_decode(deserializer);
        let mut var_frameRate = <Option<f64>>::sse_decode(deserializer);
        let mut var_videoCodec = <Option<String>>::sse_decode(deserializer);
        let mut var_audioCodec = <Option<String>>::sse_decode(deserializer);
        return crate::api::VideoProbe {
            duration_ms: var_durationMs,
            width: var_width,
            height: var_height,
            video_bitrate: var_videoBitrate,
            audio_bitrate: var_audioBitrate,
            frame_rate: var_frameRate,
            video_codec: var_videoCodec,
            audio_codec: var_audioCodec,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::ThumbnailFormat {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Png => 0.into_dart(),
            Self::Jpeg => 1.into_dart(),
            Self::Webp => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::ThumbnailFormat {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::ThumbnailFormat>
    for crate::api::ThumbnailFormat
{
    fn into_into_dart(self) -> crate::api::ThumbnailFormat {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::TimelineThumbnail {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.index.into_into_dart().into_dart(),
            self.time_sec.into_into_dart().into_dart(),
            self.image_bytes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::TimelineThumbnail {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::TimelineThumbnail>
    for crate::api::TimelineThumbnail
{
    fn into_into_dart(self) -> crate::api::TimelineThumbnail {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::TranscodeProgress {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.phase.into_into_dart().into_dart(),
            self.fraction.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::TranscodeProgress {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::TranscodeProgress>
    for crate::api::TranscodeProgress
{
    fn into_into_dart(self) -> crate::api::TranscodeProgress {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::VideoProbe {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.duration_ms.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.video_bitrate.into_into_dart().into_dart(),
            self.audio_bitrate.into_into_dart().into_dart(),
            self.frame_rate.into_into_dart().into_dart(),
            self.video_codec.into_into_dart().into_dart(),
            self.audio_codec.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::VideoProbe {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::VideoProbe> for crate::api::VideoProbe {
    fn into_into_dart(self) -> crate::api::VideoProbe {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::TimelineThumbnail, flutter_rust_bridge::for_generated::DcoCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<crate::api::TranscodeProgress, flutter_rust_bridge::for_generated::DcoCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<i64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <i64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::ThumbnailFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::ThumbnailFormat::Png => 0,
                crate::api::ThumbnailFormat::Jpeg => 1,
                crate::api::ThumbnailFormat::Webp => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::TimelineThumbnail {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.index, serializer);
        <f64>::sse_encode(self.time_sec, serializer);
        <Vec<u8>>::sse_encode(self.image_bytes, serializer);
    }
}

impl SseEncode for crate::api::TranscodeProgress {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.phase, serializer);
        <f64>::sse_encode(self.fraction, serializer);
        <Option<String>>::sse_encode(self.message, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::VideoProbe {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<i64>>::sse_encode(self.duration_ms, serializer);
        <Option<u32>>::sse_encode(self.width, serializer);
        <Option<u32>>::sse_encode(self.height, serializer);
        <Option<i64>>::sse_encode(self.video_bitrate, serializer);
        <Option<i64>>::sse_encode(self.audio_bitrate, serializer);
        <Option<f64>>::sse_encode(self.frame_rate, serializer);
        <Option<String>>::sse_encode(self.video_codec, serializer);
        <Option<String>>::sse_encode(self.audio_codec, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    // Section: dart2rust

    impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error>
        for *mut wire_cst_list_prim_u_8_strict
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
            unimplemented!()
        }
    }
    impl
        CstDecode<
            StreamSink<crate::api::TimelineThumbnail, flutter_rust_bridge::for_generated::DcoCodec>,
        > for *mut wire_cst_list_prim_u_8_strict
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> StreamSink<crate::api::TimelineThumbnail, flutter_rust_bridge::for_generated::DcoCodec>
        {
            let raw: String = self.cst_decode();
            StreamSink::deserialize(raw)
        }
    }
    impl
        CstDecode<
            StreamSink<crate::api::TranscodeProgress, flutter_rust_bridge::for_generated::DcoCodec>,
        > for *mut wire_cst_list_prim_u_8_strict
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> StreamSink<crate::api::TranscodeProgress, flutter_rust_bridge::for_generated::DcoCodec>
        {
            let raw: String = self.cst_decode();
            StreamSink::deserialize(raw)
        }
    }
    impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            let vec: Vec<u8> = self.cst_decode();
            String::from_utf8(vec).unwrap()
        }
    }
    impl CstDecode<f64> for *mut f64 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> f64 {
            unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
        }
    }
    impl CstDecode<i64> for *mut i64 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> i64 {
            unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
        }
    }
    impl CstDecode<u32> for *mut u32 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u32 {
            unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl CstDecode<crate::api::TimelineThumbnail> for wire_cst_timeline_thumbnail {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::TimelineThumbnail {
            crate::api::TimelineThumbnail {
                index: self.index.cst_decode(),
                time_sec: self.time_sec.cst_decode(),
                image_bytes: self.image_bytes.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::TranscodeProgress> for wire_cst_transcode_progress {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::TranscodeProgress {
            crate::api::TranscodeProgress {
                phase: self.phase.cst_decode(),
                fraction: self.fraction.cst_decode(),
                message: self.message.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::VideoProbe> for wire_cst_video_probe {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::VideoProbe {
            crate::api::VideoProbe {
                duration_ms: self.duration_ms.cst_decode(),
                width: self.width.cst_decode(),
                height: self.height.cst_decode(),
                video_bitrate: self.video_bitrate.cst_decode(),
                audio_bitrate: self.audio_bitrate.cst_decode(),
                frame_rate: self.frame_rate.cst_decode(),
                video_codec: self.video_codec.cst_decode(),
                audio_codec: self.audio_codec.cst_decode(),
            }
        }
    }
    impl NewWithNullPtr for wire_cst_timeline_thumbnail {
        fn new_with_null_ptr() -> Self {
            Self {
                index: Default::default(),
                time_sec: Default::default(),
                image_bytes: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_timeline_thumbnail {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_transcode_progress {
        fn new_with_null_ptr() -> Self {
            Self {
                phase: core::ptr::null_mut(),
                fraction: Default::default(),
                message: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_transcode_progress {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_video_probe {
        fn new_with_null_ptr() -> Self {
            Self {
                duration_ms: core::ptr::null_mut(),
                width: core::ptr::null_mut(),
                height: core::ptr::null_mut(),
                video_bitrate: core::ptr::null_mut(),
                audio_bitrate: core::ptr::null_mut(),
                frame_rate: core::ptr::null_mut(),
                video_codec: core::ptr::null_mut(),
                audio_codec: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_video_probe {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_wire__crate__api__probe_video(
        port_: i64,
        path: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__probe_video_impl(port_, path)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_wire__crate__api__thumbnail_image(
        port_: i64,
        path: *mut wire_cst_list_prim_u_8_strict,
        time_sec: f64,
        max_edge: u32,
        format: i32,
    ) {
        wire__crate__api__thumbnail_image_impl(port_, path, time_sec, max_edge, format)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_wire__crate__api__thumbnail_save_to_path(
        port_: i64,
        path: *mut wire_cst_list_prim_u_8_strict,
        output_path: *mut wire_cst_list_prim_u_8_strict,
        time_sec: f64,
        max_edge: u32,
        format: i32,
    ) {
        wire__crate__api__thumbnail_save_to_path_impl(
            port_,
            path,
            output_path,
            time_sec,
            max_edge,
            format,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_wire__crate__api__timeline_thumbnails(
        port_: i64,
        path: *mut wire_cst_list_prim_u_8_strict,
        frame_count: u32,
        max_edge: u32,
        format: i32,
        sink: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__timeline_thumbnails_impl(port_, path, frame_count, max_edge, format, sink)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_wire__crate__api__transcode_video(
        port_: i64,
        input_path: *mut wire_cst_list_prim_u_8_strict,
        output_path: *mut wire_cst_list_prim_u_8_strict,
        video_bitrate_kbps: u32,
        max_width: u32,
        audio_bitrate_kbps: u32,
        sink: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__transcode_video_impl(
            port_,
            input_path,
            output_path,
            video_bitrate_kbps,
            max_width,
            audio_bitrate_kbps,
            sink,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_box_autoadd_f_64(value: f64) -> *mut f64 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_box_autoadd_i_64(value: i64) -> *mut i64 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_box_autoadd_u_32(value: u32) -> *mut u32 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_list_prim_u_8_strict(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_strict {
        let ans = wire_cst_list_prim_u_8_strict {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_strict {
        ptr: *mut u8,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_timeline_thumbnail {
        index: u32,
        time_sec: f64,
        image_bytes: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_transcode_progress {
        phase: *mut wire_cst_list_prim_u_8_strict,
        fraction: f64,
        message: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_video_probe {
        duration_ms: *mut i64,
        width: *mut u32,
        height: *mut u32,
        video_bitrate: *mut i64,
        audio_bitrate: *mut i64,
        frame_rate: *mut f64,
        video_codec: *mut wire_cst_list_prim_u_8_strict,
        audio_codec: *mut wire_cst_list_prim_u_8_strict,
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    // Section: dart2rust

    impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error> for String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
            unimplemented!()
        }
    }
    impl
        CstDecode<
            StreamSink<crate::api::TimelineThumbnail, flutter_rust_bridge::for_generated::DcoCodec>,
        > for String
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> StreamSink<crate::api::TimelineThumbnail, flutter_rust_bridge::for_generated::DcoCodec>
        {
            StreamSink::deserialize(self)
        }
    }
    impl
        CstDecode<
            StreamSink<crate::api::TranscodeProgress, flutter_rust_bridge::for_generated::DcoCodec>,
        > for String
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> StreamSink<crate::api::TranscodeProgress, flutter_rust_bridge::for_generated::DcoCodec>
        {
            StreamSink::deserialize(self)
        }
    }
    impl CstDecode<String> for String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self
        }
    }
    impl CstDecode<Vec<u8>> for Box<[u8]> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.into_vec()
        }
    }
    impl CstDecode<Option<String>> for Option<String> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Option<String> {
            self.map(CstDecode::cst_decode)
        }
    }
    impl CstDecode<crate::api::TimelineThumbnail>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::TimelineThumbnail {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                3,
                "Expected 3 elements, got {}",
                self_.length()
            );
            crate::api::TimelineThumbnail {
                index: self_.get(0).cst_decode(),
                time_sec: self_.get(1).cst_decode(),
                image_bytes: self_.get(2).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::TranscodeProgress>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::TranscodeProgress {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                3,
                "Expected 3 elements, got {}",
                self_.length()
            );
            crate::api::TranscodeProgress {
                phase: self_.get(0).cst_decode(),
                fraction: self_.get(1).cst_decode(),
                message: self_.get(2).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::VideoProbe>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::VideoProbe {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                8,
                "Expected 8 elements, got {}",
                self_.length()
            );
            crate::api::VideoProbe {
                duration_ms: self_.get(0).cst_decode(),
                width: self_.get(1).cst_decode(),
                height: self_.get(2).cst_decode(),
                video_bitrate: self_.get(3).cst_decode(),
                audio_bitrate: self_.get(4).cst_decode(),
                frame_rate: self_.get(5).cst_decode(),
                video_codec: self_.get(6).cst_decode(),
                audio_codec: self_.get(7).cst_decode(),
            }
        }
    }
    impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
            unimplemented!()
        }
    }
    impl
        CstDecode<
            StreamSink<crate::api::TimelineThumbnail, flutter_rust_bridge::for_generated::DcoCodec>,
        > for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> StreamSink<crate::api::TimelineThumbnail, flutter_rust_bridge::for_generated::DcoCodec>
        {
            StreamSink::deserialize(self.as_string().expect("should be a string"))
        }
    }
    impl
        CstDecode<
            StreamSink<crate::api::TranscodeProgress, flutter_rust_bridge::for_generated::DcoCodec>,
        > for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> StreamSink<crate::api::TranscodeProgress, flutter_rust_bridge::for_generated::DcoCodec>
        {
            StreamSink::deserialize(self.as_string().expect("should be a string"))
        }
    }
    impl CstDecode<String> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self.as_string().expect("non-UTF-8 string, or not a string")
        }
    }
    impl CstDecode<f64> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> f64 {
            self.unchecked_into_f64() as _
        }
    }
    impl CstDecode<i32> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> i32 {
            self.unchecked_into_f64() as _
        }
    }
    impl CstDecode<i64> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> i64 {
            ::std::convert::TryInto::<i64>::try_into(self).unwrap() as _
        }
    }
    impl CstDecode<Vec<u8>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.unchecked_into::<flutter_rust_bridge::for_generated::js_sys::Uint8Array>()
                .to_vec()
                .into()
        }
    }
    impl CstDecode<crate::api::ThumbnailFormat>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::ThumbnailFormat {
            (self.unchecked_into_f64() as i32).cst_decode()
        }
    }
    impl CstDecode<u32> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u32 {
            self.unchecked_into_f64() as _
        }
    }
    impl CstDecode<u8> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u8 {
            self.unchecked_into_f64() as _
        }
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__probe_video(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        path: String,
    ) {
        wire__crate__api__probe_video_impl(port_, path)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__thumbnail_image(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        path: String,
        time_sec: f64,
        max_edge: u32,
        format: i32,
    ) {
        wire__crate__api__thumbnail_image_impl(port_, path, time_sec, max_edge, format)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__thumbnail_save_to_path(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        path: String,
        output_path: String,
        time_sec: f64,
        max_edge: u32,
        format: i32,
    ) {
        wire__crate__api__thumbnail_save_to_path_impl(
            port_,
            path,
            output_path,
            time_sec,
            max_edge,
            format,
        )
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__timeline_thumbnails(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        path: String,
        frame_count: u32,
        max_edge: u32,
        format: i32,
        sink: String,
    ) {
        wire__crate__api__timeline_thumbnails_impl(port_, path, frame_count, max_edge, format, sink)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__transcode_video(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        input_path: String,
        output_path: String,
        video_bitrate_kbps: u32,
        max_width: u32,
        audio_bitrate_kbps: u32,
        sink: String,
    ) {
        wire__crate__api__transcode_video_impl(
            port_,
            input_path,
            output_path,
            video_bitrate_kbps,
            max_width,
            audio_bitrate_kbps,
            sink,
        )
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
