// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class DeliveryEstimate {
  final DeliveryProfileId profileId;
  final int width;
  final int height;
  final BigInt estimatedSizeBytes;
  final int videoBitrateKbps;
  final int audioBitrateKbps;
  final BigInt estimatedEncodeTimeMs;

  const DeliveryEstimate({
    required this.profileId,
    required this.width,
    required this.height,
    required this.estimatedSizeBytes,
    required this.videoBitrateKbps,
    required this.audioBitrateKbps,
    required this.estimatedEncodeTimeMs,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^
      width.hashCode ^
      height.hashCode ^
      estimatedSizeBytes.hashCode ^
      videoBitrateKbps.hashCode ^
      audioBitrateKbps.hashCode ^
      estimatedEncodeTimeMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeliveryEstimate &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          width == other.width &&
          height == other.height &&
          estimatedSizeBytes == other.estimatedSizeBytes &&
          videoBitrateKbps == other.videoBitrateKbps &&
          audioBitrateKbps == other.audioBitrateKbps &&
          estimatedEncodeTimeMs == other.estimatedEncodeTimeMs;
}

enum DeliveryProfileId { hd720, sd480 }

class VideoDeliveryEstimates {
  final DeliveryEstimate hd720;
  final DeliveryEstimate sd480;

  const VideoDeliveryEstimates({required this.hd720, required this.sd480});

  @override
  int get hashCode => hd720.hashCode ^ sd480.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoDeliveryEstimates &&
          runtimeType == other.runtimeType &&
          hd720 == other.hd720 &&
          sd480 == other.sd480;
}
