// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> log({
  required String file,
  int? line,
  required LogLevel level,
  required String target,
  required String message,
}) => RustLib.instance.api.crateApiLoggerLog(
  file: file,
  line: line,
  level: level,
  target: target,
  message: message,
);

Future<void> debugThreads() =>
    RustLib.instance.api.crateApiLoggerDebugThreads();

Future<void> initLogger({
  required LogLevel logLevel,
  required bool writeToStdoutOrSystem,
  WriteToFiles? writeToFiles,
  required bool useLightweightTokioRuntime,
}) => RustLib.instance.api.crateApiLoggerInitLogger(
  logLevel: logLevel,
  writeToStdoutOrSystem: writeToStdoutOrSystem,
  writeToFiles: writeToFiles,
  useLightweightTokioRuntime: useLightweightTokioRuntime,
);

Future<void> reloadTracingFileWriter({required WriteToFiles writeToFiles}) =>
    RustLib.instance.api.crateApiLoggerReloadTracingFileWriter(
      writeToFiles: writeToFiles,
    );

enum LogLevel { error, warn, info, debug, trace }

class WriteToFiles {
  final String path;
  final String filePrefix;
  final String? fileSuffix;
  final BigInt? maxFiles;

  const WriteToFiles({
    required this.path,
    required this.filePrefix,
    this.fileSuffix,
    this.maxFiles,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      filePrefix.hashCode ^
      fileSuffix.hashCode ^
      maxFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WriteToFiles &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          filePrefix == other.filePrefix &&
          fileSuffix == other.fileSuffix &&
          maxFiles == other.maxFiles;
}
