// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CompressParams`, `CompressProgress`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Exposed via FRB
Future<VideoInfo> getVideoInfo({required String path}) =>
    RustLib.instance.api.crateApiMediaGetVideoInfo(path: path);

/// returns PNG bytes of a thumbnail
Future<Uint8List> generateThumbnail(
        {required String path, required ThumbnailParams params}) =>
    RustLib.instance.api
        .crateApiMediaGenerateThumbnail(path: path, params: params);

class ThumbnailParams {
  final BigInt timeMs;
  final int maxWidth;
  final int maxHeight;

  const ThumbnailParams({
    required this.timeMs,
    required this.maxWidth,
    required this.maxHeight,
  });

  @override
  int get hashCode => timeMs.hashCode ^ maxWidth.hashCode ^ maxHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThumbnailParams &&
          runtimeType == other.runtimeType &&
          timeMs == other.timeMs &&
          maxWidth == other.maxWidth &&
          maxHeight == other.maxHeight;
}

class VideoInfo {
  final BigInt durationMs;
  final int width;
  final int height;
  final BigInt sizeBytes;
  final BigInt? bitrate;
  final String? codecName;
  final String? formatName;

  const VideoInfo({
    required this.durationMs,
    required this.width,
    required this.height,
    required this.sizeBytes,
    this.bitrate,
    this.codecName,
    this.formatName,
  });

  @override
  int get hashCode =>
      durationMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      sizeBytes.hashCode ^
      bitrate.hashCode ^
      codecName.hashCode ^
      formatName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoInfo &&
          runtimeType == other.runtimeType &&
          durationMs == other.durationMs &&
          width == other.width &&
          height == other.height &&
          sizeBytes == other.sizeBytes &&
          bitrate == other.bitrate &&
          codecName == other.codecName &&
          formatName == other.formatName;
}
