// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = DcoCodec,
    default_rust_opaque = RustOpaqueNom,
    default_rust_auto_opaque = RustAutoOpaqueNom,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1166833132;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__media__compress_video_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    path: impl CstDecode<String>,
    output_path: impl CstDecode<String>,
    params: impl CstDecode<crate::api::media::CompressParams>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "compress_video",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_path = path.cst_decode();
            let api_output_path = output_path.cst_decode();
            let api_params = params.cst_decode();
            move |context| {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::media::compress_video(
                            api_path,
                            api_output_path,
                            api_params,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__media__estimate_compression_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    path: impl CstDecode<String>,
    temp_output_path: impl CstDecode<String>,
    params: impl CstDecode<crate::api::media::CompressParams>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "estimate_compression",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_path = path.cst_decode();
            let api_temp_output_path = temp_output_path.cst_decode();
            let api_params = params.cst_decode();
            move |context| {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::media::estimate_compression(
                            api_path,
                            api_temp_output_path,
                            api_params,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__media__generate_image_thumbnail_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    path: impl CstDecode<String>,
    output_path: impl CstDecode<String>,
    params: impl CstDecode<Option<crate::api::media::ImageThumbnailParams>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "generate_image_thumbnail",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_path = path.cst_decode();
            let api_output_path = output_path.cst_decode();
            let api_params = params.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::media::generate_image_thumbnail(
                            api_path,
                            api_output_path,
                            api_params,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__media__generate_video_thumbnail_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    path: impl CstDecode<String>,
    output_path: impl CstDecode<String>,
    params: impl CstDecode<crate::api::media::VideoThumbnailParams>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::DcoCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "generate_video_thumbnail",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_path = path.cst_decode();
            let api_output_path = output_path.cst_decode();
            let api_params = params.cst_decode();
            move |context| async move {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::media::generate_video_thumbnail(
                            api_path,
                            api_output_path,
                            api_params,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__media__generate_video_timeline_thumbnails_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    path: impl CstDecode<String>,
    output_path: impl CstDecode<String>,
    params: impl CstDecode<Option<crate::api::media::ImageThumbnailParams>>,
    num_thumbnails: impl CstDecode<u32>,
    sink: impl CstDecode<StreamSink<String, flutter_rust_bridge::for_generated::DcoCodec>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "generate_video_timeline_thumbnails",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_path = path.cst_decode();
            let api_output_path = output_path.cst_decode();
            let api_params = params.cst_decode();
            let api_num_thumbnails = num_thumbnails.cst_decode();
            let api_sink = sink.cst_decode();
            move |context| {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::media::generate_video_timeline_thumbnails(
                            api_path,
                            api_output_path,
                            api_params,
                            api_num_thumbnails,
                            api_sink,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__media__get_video_info_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    path: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_video_info",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_path = path.cst_decode();
            move |context| {
                transform_result_dco::<_, _, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::media::get_video_info(api_path)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__media__output_format_extension_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<crate::api::media::OutputFormat>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "output_format_extension",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::media::OutputFormat::extension(&api_that);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__media__thumbnail_size_type_dimensions_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<crate::api::media::ThumbnailSizeType>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "thumbnail_size_type_dimensions",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        crate::api::media::ThumbnailSizeType::dimensions(&api_that),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl CstDecode<i32> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> i32 {
        self
    }
}
impl CstDecode<crate::api::media::OutputFormat> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> crate::api::media::OutputFormat {
        match self {
            0 => crate::api::media::OutputFormat::WEBP,
            1 => crate::api::media::OutputFormat::JPEG,
            2 => crate::api::media::OutputFormat::PNG,
            _ => unreachable!("Invalid variant for OutputFormat: {}", self),
        }
    }
}
impl CstDecode<u32> for u32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u32 {
        self
    }
}
impl CstDecode<u64> for u64 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u64 {
        self
    }
}
impl CstDecode<u8> for u8 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u8 {
        self
    }
}
impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode for StreamSink<String, flutter_rust_bridge::for_generated::DcoCodec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::media::CompressParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_targetBitrateKbps = <u32>::sse_decode(deserializer);
        let mut var_preset = <Option<String>>::sse_decode(deserializer);
        let mut var_crf = <Option<u8>>::sse_decode(deserializer);
        let mut var_width = <Option<u32>>::sse_decode(deserializer);
        let mut var_height = <Option<u32>>::sse_decode(deserializer);
        return crate::api::media::CompressParams {
            target_bitrate_kbps: var_targetBitrateKbps,
            preset: var_preset,
            crf: var_crf,
            width: var_width,
            height: var_height,
        };
    }
}

impl SseDecode for crate::api::media::CompressionEstimate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_estimatedSizeBytes = <u64>::sse_decode(deserializer);
        let mut var_estimatedDurationMs = <u64>::sse_decode(deserializer);
        return crate::api::media::CompressionEstimate {
            estimated_size_bytes: var_estimatedSizeBytes,
            estimated_duration_ms: var_estimatedDurationMs,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::media::ImageThumbnailParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sizeType =
            <Option<crate::api::media::ThumbnailSizeType>>::sse_decode(deserializer);
        let mut var_format = <Option<crate::api::media::OutputFormat>>::sse_decode(deserializer);
        return crate::api::media::ImageThumbnailParams {
            size_type: var_sizeType,
            format: var_format,
        };
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::media::ResolutionPreset> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::media::ResolutionPreset>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::media::ImageThumbnailParams> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::media::ImageThumbnailParams>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::media::OutputFormat> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::media::OutputFormat>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::media::ThumbnailSizeType> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::media::ThumbnailSizeType>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u8>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::media::OutputFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::media::OutputFormat::WEBP,
            1 => crate::api::media::OutputFormat::JPEG,
            2 => crate::api::media::OutputFormat::PNG,
            _ => unreachable!("Invalid variant for OutputFormat: {}", inner),
        };
    }
}

impl SseDecode for (u32, u32) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_field0 = <u32>::sse_decode(deserializer);
        let mut var_field1 = <u32>::sse_decode(deserializer);
        return (var_field0, var_field1);
    }
}

impl SseDecode for crate::api::media::ResolutionPreset {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        let mut var_bitrate = <u64>::sse_decode(deserializer);
        let mut var_crf = <u8>::sse_decode(deserializer);
        return crate::api::media::ResolutionPreset {
            name: var_name,
            width: var_width,
            height: var_height,
            bitrate: var_bitrate,
            crf: var_crf,
        };
    }
}

impl SseDecode for crate::api::media::ThumbnailSizeType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::media::ThumbnailSizeType::Icon;
            }
            1 => {
                return crate::api::media::ThumbnailSizeType::Small;
            }
            2 => {
                return crate::api::media::ThumbnailSizeType::Medium;
            }
            3 => {
                return crate::api::media::ThumbnailSizeType::Large;
            }
            4 => {
                return crate::api::media::ThumbnailSizeType::Larger;
            }
            5 => {
                let mut var_field0 = <(u32, u32)>::sse_decode(deserializer);
                return crate::api::media::ThumbnailSizeType::Custom(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::media::VideoInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_durationMs = <u64>::sse_decode(deserializer);
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        let mut var_sizeBytes = <u64>::sse_decode(deserializer);
        let mut var_bitrate = <Option<u64>>::sse_decode(deserializer);
        let mut var_codecName = <Option<String>>::sse_decode(deserializer);
        let mut var_formatName = <Option<String>>::sse_decode(deserializer);
        let mut var_suggestions =
            <Vec<crate::api::media::ResolutionPreset>>::sse_decode(deserializer);
        return crate::api::media::VideoInfo {
            duration_ms: var_durationMs,
            width: var_width,
            height: var_height,
            size_bytes: var_sizeBytes,
            bitrate: var_bitrate,
            codec_name: var_codecName,
            format_name: var_formatName,
            suggestions: var_suggestions,
        };
    }
}

impl SseDecode for crate::api::media::VideoThumbnailParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_timeMs = <u64>::sse_decode(deserializer);
        let mut var_sizeType =
            <Option<crate::api::media::ThumbnailSizeType>>::sse_decode(deserializer);
        let mut var_format = <Option<crate::api::media::OutputFormat>>::sse_decode(deserializer);
        return crate::api::media::VideoThumbnailParams {
            time_ms: var_timeMs,
            size_type: var_sizeType,
            format: var_format,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::CompressParams {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.target_bitrate_kbps.into_into_dart().into_dart(),
            self.preset.into_into_dart().into_dart(),
            self.crf.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::CompressParams
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::CompressParams>
    for crate::api::media::CompressParams
{
    fn into_into_dart(self) -> crate::api::media::CompressParams {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::CompressionEstimate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.estimated_size_bytes.into_into_dart().into_dart(),
            self.estimated_duration_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::CompressionEstimate
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::CompressionEstimate>
    for crate::api::media::CompressionEstimate
{
    fn into_into_dart(self) -> crate::api::media::CompressionEstimate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::ImageThumbnailParams {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.size_type.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::ImageThumbnailParams
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::ImageThumbnailParams>
    for crate::api::media::ImageThumbnailParams
{
    fn into_into_dart(self) -> crate::api::media::ImageThumbnailParams {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::OutputFormat {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::WEBP => 0.into_dart(),
            Self::JPEG => 1.into_dart(),
            Self::PNG => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::OutputFormat
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::OutputFormat>
    for crate::api::media::OutputFormat
{
    fn into_into_dart(self) -> crate::api::media::OutputFormat {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::ResolutionPreset {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.bitrate.into_into_dart().into_dart(),
            self.crf.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::ResolutionPreset
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::ResolutionPreset>
    for crate::api::media::ResolutionPreset
{
    fn into_into_dart(self) -> crate::api::media::ResolutionPreset {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::ThumbnailSizeType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::media::ThumbnailSizeType::Icon => [0.into_dart()].into_dart(),
            crate::api::media::ThumbnailSizeType::Small => [1.into_dart()].into_dart(),
            crate::api::media::ThumbnailSizeType::Medium => [2.into_dart()].into_dart(),
            crate::api::media::ThumbnailSizeType::Large => [3.into_dart()].into_dart(),
            crate::api::media::ThumbnailSizeType::Larger => [4.into_dart()].into_dart(),
            crate::api::media::ThumbnailSizeType::Custom(field0) => {
                [5.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::ThumbnailSizeType
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::ThumbnailSizeType>
    for crate::api::media::ThumbnailSizeType
{
    fn into_into_dart(self) -> crate::api::media::ThumbnailSizeType {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::VideoInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.duration_ms.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
            self.size_bytes.into_into_dart().into_dart(),
            self.bitrate.into_into_dart().into_dart(),
            self.codec_name.into_into_dart().into_dart(),
            self.format_name.into_into_dart().into_dart(),
            self.suggestions.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::media::VideoInfo {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::VideoInfo>
    for crate::api::media::VideoInfo
{
    fn into_into_dart(self) -> crate::api::media::VideoInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::media::VideoThumbnailParams {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.time_ms.into_into_dart().into_dart(),
            self.size_type.into_into_dart().into_dart(),
            self.format.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::media::VideoThumbnailParams
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::media::VideoThumbnailParams>
    for crate::api::media::VideoThumbnailParams
{
    fn into_into_dart(self) -> crate::api::media::VideoThumbnailParams {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode for StreamSink<String, flutter_rust_bridge::for_generated::DcoCodec> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::media::CompressParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.target_bitrate_kbps, serializer);
        <Option<String>>::sse_encode(self.preset, serializer);
        <Option<u8>>::sse_encode(self.crf, serializer);
        <Option<u32>>::sse_encode(self.width, serializer);
        <Option<u32>>::sse_encode(self.height, serializer);
    }
}

impl SseEncode for crate::api::media::CompressionEstimate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.estimated_size_bytes, serializer);
        <u64>::sse_encode(self.estimated_duration_ms, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::media::ImageThumbnailParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<crate::api::media::ThumbnailSizeType>>::sse_encode(self.size_type, serializer);
        <Option<crate::api::media::OutputFormat>>::sse_encode(self.format, serializer);
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::media::ResolutionPreset> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::media::ResolutionPreset>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::media::ImageThumbnailParams> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::media::ImageThumbnailParams>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::media::OutputFormat> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::media::OutputFormat>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::media::ThumbnailSizeType> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::media::ThumbnailSizeType>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u8>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::media::OutputFormat {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::media::OutputFormat::WEBP => 0,
                crate::api::media::OutputFormat::JPEG => 1,
                crate::api::media::OutputFormat::PNG => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for (u32, u32) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.0, serializer);
        <u32>::sse_encode(self.1, serializer);
    }
}

impl SseEncode for crate::api::media::ResolutionPreset {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
        <u64>::sse_encode(self.bitrate, serializer);
        <u8>::sse_encode(self.crf, serializer);
    }
}

impl SseEncode for crate::api::media::ThumbnailSizeType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::media::ThumbnailSizeType::Icon => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::media::ThumbnailSizeType::Small => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::media::ThumbnailSizeType::Medium => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::media::ThumbnailSizeType::Large => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::media::ThumbnailSizeType::Larger => {
                <i32>::sse_encode(4, serializer);
            }
            crate::api::media::ThumbnailSizeType::Custom(field0) => {
                <i32>::sse_encode(5, serializer);
                <(u32, u32)>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::media::VideoInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.duration_ms, serializer);
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
        <u64>::sse_encode(self.size_bytes, serializer);
        <Option<u64>>::sse_encode(self.bitrate, serializer);
        <Option<String>>::sse_encode(self.codec_name, serializer);
        <Option<String>>::sse_encode(self.format_name, serializer);
        <Vec<crate::api::media::ResolutionPreset>>::sse_encode(self.suggestions, serializer);
    }
}

impl SseEncode for crate::api::media::VideoThumbnailParams {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.time_ms, serializer);
        <Option<crate::api::media::ThumbnailSizeType>>::sse_encode(self.size_type, serializer);
        <Option<crate::api::media::OutputFormat>>::sse_encode(self.format, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    // Section: dart2rust

    impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error>
        for *mut wire_cst_list_prim_u_8_strict
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
            unimplemented!()
        }
    }
    impl CstDecode<StreamSink<String, flutter_rust_bridge::for_generated::DcoCodec>>
        for *mut wire_cst_list_prim_u_8_strict
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> StreamSink<String, flutter_rust_bridge::for_generated::DcoCodec> {
            let raw: String = self.cst_decode();
            StreamSink::deserialize(raw)
        }
    }
    impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            let vec: Vec<u8> = self.cst_decode();
            String::from_utf8(vec).unwrap()
        }
    }
    impl CstDecode<crate::api::media::CompressParams> for *mut wire_cst_compress_params {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::CompressParams {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::media::CompressParams>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<crate::api::media::ImageThumbnailParams> for *mut wire_cst_image_thumbnail_params {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::ImageThumbnailParams {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::media::ImageThumbnailParams>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<crate::api::media::OutputFormat> for *mut i32 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::OutputFormat {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::media::OutputFormat>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<(u32, u32)> for *mut wire_cst_record_u_32_u_32 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> (u32, u32) {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<(u32, u32)>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<crate::api::media::ThumbnailSizeType> for *mut wire_cst_thumbnail_size_type {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::ThumbnailSizeType {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::media::ThumbnailSizeType>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<u32> for *mut u32 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u32 {
            unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
        }
    }
    impl CstDecode<u64> for *mut u64 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u64 {
            unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
        }
    }
    impl CstDecode<u8> for *mut u8 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u8 {
            unsafe { *flutter_rust_bridge::for_generated::box_from_leak_ptr(self) }
        }
    }
    impl CstDecode<crate::api::media::VideoThumbnailParams> for *mut wire_cst_video_thumbnail_params {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::VideoThumbnailParams {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::media::VideoThumbnailParams>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<crate::api::media::CompressParams> for wire_cst_compress_params {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::CompressParams {
            crate::api::media::CompressParams {
                target_bitrate_kbps: self.target_bitrate_kbps.cst_decode(),
                preset: self.preset.cst_decode(),
                crf: self.crf.cst_decode(),
                width: self.width.cst_decode(),
                height: self.height.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::media::CompressionEstimate> for wire_cst_compression_estimate {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::CompressionEstimate {
            crate::api::media::CompressionEstimate {
                estimated_size_bytes: self.estimated_size_bytes.cst_decode(),
                estimated_duration_ms: self.estimated_duration_ms.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::media::ImageThumbnailParams> for wire_cst_image_thumbnail_params {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::ImageThumbnailParams {
            crate::api::media::ImageThumbnailParams {
                size_type: self.size_type.cst_decode(),
                format: self.format.cst_decode(),
            }
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl CstDecode<Vec<crate::api::media::ResolutionPreset>> for *mut wire_cst_list_resolution_preset {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::media::ResolutionPreset> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<(u32, u32)> for wire_cst_record_u_32_u_32 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> (u32, u32) {
            (self.field0.cst_decode(), self.field1.cst_decode())
        }
    }
    impl CstDecode<crate::api::media::ResolutionPreset> for wire_cst_resolution_preset {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::ResolutionPreset {
            crate::api::media::ResolutionPreset {
                name: self.name.cst_decode(),
                width: self.width.cst_decode(),
                height: self.height.cst_decode(),
                bitrate: self.bitrate.cst_decode(),
                crf: self.crf.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::media::ThumbnailSizeType> for wire_cst_thumbnail_size_type {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::ThumbnailSizeType {
            match self.tag {
                0 => crate::api::media::ThumbnailSizeType::Icon,
                1 => crate::api::media::ThumbnailSizeType::Small,
                2 => crate::api::media::ThumbnailSizeType::Medium,
                3 => crate::api::media::ThumbnailSizeType::Large,
                4 => crate::api::media::ThumbnailSizeType::Larger,
                5 => {
                    let ans = unsafe { self.kind.Custom };
                    crate::api::media::ThumbnailSizeType::Custom(ans.field0.cst_decode())
                }
                _ => unreachable!(),
            }
        }
    }
    impl CstDecode<crate::api::media::VideoInfo> for wire_cst_video_info {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::VideoInfo {
            crate::api::media::VideoInfo {
                duration_ms: self.duration_ms.cst_decode(),
                width: self.width.cst_decode(),
                height: self.height.cst_decode(),
                size_bytes: self.size_bytes.cst_decode(),
                bitrate: self.bitrate.cst_decode(),
                codec_name: self.codec_name.cst_decode(),
                format_name: self.format_name.cst_decode(),
                suggestions: self.suggestions.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::media::VideoThumbnailParams> for wire_cst_video_thumbnail_params {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::VideoThumbnailParams {
            crate::api::media::VideoThumbnailParams {
                time_ms: self.time_ms.cst_decode(),
                size_type: self.size_type.cst_decode(),
                format: self.format.cst_decode(),
            }
        }
    }
    impl NewWithNullPtr for wire_cst_compress_params {
        fn new_with_null_ptr() -> Self {
            Self {
                target_bitrate_kbps: Default::default(),
                preset: core::ptr::null_mut(),
                crf: core::ptr::null_mut(),
                width: core::ptr::null_mut(),
                height: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_compress_params {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_compression_estimate {
        fn new_with_null_ptr() -> Self {
            Self {
                estimated_size_bytes: Default::default(),
                estimated_duration_ms: Default::default(),
            }
        }
    }
    impl Default for wire_cst_compression_estimate {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_image_thumbnail_params {
        fn new_with_null_ptr() -> Self {
            Self {
                size_type: core::ptr::null_mut(),
                format: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_image_thumbnail_params {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_record_u_32_u_32 {
        fn new_with_null_ptr() -> Self {
            Self {
                field0: Default::default(),
                field1: Default::default(),
            }
        }
    }
    impl Default for wire_cst_record_u_32_u_32 {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_resolution_preset {
        fn new_with_null_ptr() -> Self {
            Self {
                name: core::ptr::null_mut(),
                width: Default::default(),
                height: Default::default(),
                bitrate: Default::default(),
                crf: Default::default(),
            }
        }
    }
    impl Default for wire_cst_resolution_preset {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_thumbnail_size_type {
        fn new_with_null_ptr() -> Self {
            Self {
                tag: -1,
                kind: ThumbnailSizeTypeKind { nil__: () },
            }
        }
    }
    impl Default for wire_cst_thumbnail_size_type {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_video_info {
        fn new_with_null_ptr() -> Self {
            Self {
                duration_ms: Default::default(),
                width: Default::default(),
                height: Default::default(),
                size_bytes: Default::default(),
                bitrate: core::ptr::null_mut(),
                codec_name: core::ptr::null_mut(),
                format_name: core::ptr::null_mut(),
                suggestions: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_video_info {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_video_thumbnail_params {
        fn new_with_null_ptr() -> Self {
            Self {
                time_ms: Default::default(),
                size_type: core::ptr::null_mut(),
                format: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_video_thumbnail_params {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_wire__crate__api__media__compress_video(
        port_: i64,
        path: *mut wire_cst_list_prim_u_8_strict,
        output_path: *mut wire_cst_list_prim_u_8_strict,
        params: *mut wire_cst_compress_params,
    ) {
        wire__crate__api__media__compress_video_impl(port_, path, output_path, params)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_wire__crate__api__media__estimate_compression(
        port_: i64,
        path: *mut wire_cst_list_prim_u_8_strict,
        temp_output_path: *mut wire_cst_list_prim_u_8_strict,
        params: *mut wire_cst_compress_params,
    ) {
        wire__crate__api__media__estimate_compression_impl(port_, path, temp_output_path, params)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_wire__crate__api__media__generate_image_thumbnail(
        port_: i64,
        path: *mut wire_cst_list_prim_u_8_strict,
        output_path: *mut wire_cst_list_prim_u_8_strict,
        params: *mut wire_cst_image_thumbnail_params,
    ) {
        wire__crate__api__media__generate_image_thumbnail_impl(port_, path, output_path, params)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_wire__crate__api__media__generate_video_thumbnail(
        port_: i64,
        path: *mut wire_cst_list_prim_u_8_strict,
        output_path: *mut wire_cst_list_prim_u_8_strict,
        params: *mut wire_cst_video_thumbnail_params,
    ) {
        wire__crate__api__media__generate_video_thumbnail_impl(port_, path, output_path, params)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_wire__crate__api__media__generate_video_timeline_thumbnails(
        port_: i64,
        path: *mut wire_cst_list_prim_u_8_strict,
        output_path: *mut wire_cst_list_prim_u_8_strict,
        params: *mut wire_cst_image_thumbnail_params,
        num_thumbnails: u32,
        sink: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__media__generate_video_timeline_thumbnails_impl(
            port_,
            path,
            output_path,
            params,
            num_thumbnails,
            sink,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_wire__crate__api__media__get_video_info(
        port_: i64,
        path: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__media__get_video_info_impl(port_, path)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_wire__crate__api__media__output_format_extension(
        port_: i64,
        that: i32,
    ) {
        wire__crate__api__media__output_format_extension_impl(port_, that)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_wire__crate__api__media__thumbnail_size_type_dimensions(
        port_: i64,
        that: *mut wire_cst_thumbnail_size_type,
    ) {
        wire__crate__api__media__thumbnail_size_type_dimensions_impl(port_, that)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_box_autoadd_compress_params(
    ) -> *mut wire_cst_compress_params {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_compress_params::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_box_autoadd_image_thumbnail_params(
    ) -> *mut wire_cst_image_thumbnail_params {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_image_thumbnail_params::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_box_autoadd_output_format(value: i32) -> *mut i32 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_box_autoadd_record_u_32_u_32(
    ) -> *mut wire_cst_record_u_32_u_32 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_record_u_32_u_32::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_box_autoadd_thumbnail_size_type(
    ) -> *mut wire_cst_thumbnail_size_type {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_thumbnail_size_type::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_box_autoadd_u_32(value: u32) -> *mut u32 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_box_autoadd_u_64(value: u64) -> *mut u64 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_box_autoadd_u_8(value: u8) -> *mut u8 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_box_autoadd_video_thumbnail_params(
    ) -> *mut wire_cst_video_thumbnail_params {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_video_thumbnail_params::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_list_prim_u_8_strict(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_strict {
        let ans = wire_cst_list_prim_u_8_strict {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_media_cst_new_list_resolution_preset(
        len: i32,
    ) -> *mut wire_cst_list_resolution_preset {
        let wrap = wire_cst_list_resolution_preset {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <wire_cst_resolution_preset>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_compress_params {
        target_bitrate_kbps: u32,
        preset: *mut wire_cst_list_prim_u_8_strict,
        crf: *mut u8,
        width: *mut u32,
        height: *mut u32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_compression_estimate {
        estimated_size_bytes: u64,
        estimated_duration_ms: u64,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_image_thumbnail_params {
        size_type: *mut wire_cst_thumbnail_size_type,
        format: *mut i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_strict {
        ptr: *mut u8,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_resolution_preset {
        ptr: *mut wire_cst_resolution_preset,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_record_u_32_u_32 {
        field0: u32,
        field1: u32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_resolution_preset {
        name: *mut wire_cst_list_prim_u_8_strict,
        width: u32,
        height: u32,
        bitrate: u64,
        crf: u8,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_thumbnail_size_type {
        tag: i32,
        kind: ThumbnailSizeTypeKind,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub union ThumbnailSizeTypeKind {
        Custom: wire_cst_ThumbnailSizeType_Custom,
        nil__: (),
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_ThumbnailSizeType_Custom {
        field0: *mut wire_cst_record_u_32_u_32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_video_info {
        duration_ms: u64,
        width: u32,
        height: u32,
        size_bytes: u64,
        bitrate: *mut u64,
        codec_name: *mut wire_cst_list_prim_u_8_strict,
        format_name: *mut wire_cst_list_prim_u_8_strict,
        suggestions: *mut wire_cst_list_resolution_preset,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_video_thumbnail_params {
        time_ms: u64,
        size_type: *mut wire_cst_thumbnail_size_type,
        format: *mut i32,
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    // Section: dart2rust

    impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error> for String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
            unimplemented!()
        }
    }
    impl CstDecode<StreamSink<String, flutter_rust_bridge::for_generated::DcoCodec>> for String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> StreamSink<String, flutter_rust_bridge::for_generated::DcoCodec> {
            StreamSink::deserialize(self)
        }
    }
    impl CstDecode<String> for String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self
        }
    }
    impl CstDecode<crate::api::media::CompressParams>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::CompressParams {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                5,
                "Expected 5 elements, got {}",
                self_.length()
            );
            crate::api::media::CompressParams {
                target_bitrate_kbps: self_.get(0).cst_decode(),
                preset: self_.get(1).cst_decode(),
                crf: self_.get(2).cst_decode(),
                width: self_.get(3).cst_decode(),
                height: self_.get(4).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::media::CompressionEstimate>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::CompressionEstimate {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                2,
                "Expected 2 elements, got {}",
                self_.length()
            );
            crate::api::media::CompressionEstimate {
                estimated_size_bytes: self_.get(0).cst_decode(),
                estimated_duration_ms: self_.get(1).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::media::ImageThumbnailParams>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::ImageThumbnailParams {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                2,
                "Expected 2 elements, got {}",
                self_.length()
            );
            crate::api::media::ImageThumbnailParams {
                size_type: self_.get(0).cst_decode(),
                format: self_.get(1).cst_decode(),
            }
        }
    }
    impl CstDecode<Vec<u8>> for Box<[u8]> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.into_vec()
        }
    }
    impl CstDecode<Vec<crate::api::media::ResolutionPreset>>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<crate::api::media::ResolutionPreset> {
            self.dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap()
                .iter()
                .map(CstDecode::cst_decode)
                .collect()
        }
    }
    impl CstDecode<Option<String>> for Option<String> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Option<String> {
            self.map(CstDecode::cst_decode)
        }
    }
    impl CstDecode<(u32, u32)> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> (u32, u32) {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                2,
                "Expected 2 elements, got {}",
                self_.length()
            );
            (self_.get(0).cst_decode(), self_.get(1).cst_decode())
        }
    }
    impl CstDecode<crate::api::media::ResolutionPreset>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::ResolutionPreset {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                5,
                "Expected 5 elements, got {}",
                self_.length()
            );
            crate::api::media::ResolutionPreset {
                name: self_.get(0).cst_decode(),
                width: self_.get(1).cst_decode(),
                height: self_.get(2).cst_decode(),
                bitrate: self_.get(3).cst_decode(),
                crf: self_.get(4).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::media::ThumbnailSizeType>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::ThumbnailSizeType {
            let self_ = self.unchecked_into::<flutter_rust_bridge::for_generated::js_sys::Array>();
            match self_.get(0).unchecked_into_f64() as _ {
                0 => crate::api::media::ThumbnailSizeType::Icon,
                1 => crate::api::media::ThumbnailSizeType::Small,
                2 => crate::api::media::ThumbnailSizeType::Medium,
                3 => crate::api::media::ThumbnailSizeType::Large,
                4 => crate::api::media::ThumbnailSizeType::Larger,
                5 => crate::api::media::ThumbnailSizeType::Custom(self_.get(1).cst_decode()),
                _ => unreachable!(),
            }
        }
    }
    impl CstDecode<crate::api::media::VideoInfo>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::VideoInfo {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                8,
                "Expected 8 elements, got {}",
                self_.length()
            );
            crate::api::media::VideoInfo {
                duration_ms: self_.get(0).cst_decode(),
                width: self_.get(1).cst_decode(),
                height: self_.get(2).cst_decode(),
                size_bytes: self_.get(3).cst_decode(),
                bitrate: self_.get(4).cst_decode(),
                codec_name: self_.get(5).cst_decode(),
                format_name: self_.get(6).cst_decode(),
                suggestions: self_.get(7).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::media::VideoThumbnailParams>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::VideoThumbnailParams {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                3,
                "Expected 3 elements, got {}",
                self_.length()
            );
            crate::api::media::VideoThumbnailParams {
                time_ms: self_.get(0).cst_decode(),
                size_type: self_.get(1).cst_decode(),
                format: self_.get(2).cst_decode(),
            }
        }
    }
    impl CstDecode<flutter_rust_bridge::for_generated::anyhow::Error>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> flutter_rust_bridge::for_generated::anyhow::Error {
            unimplemented!()
        }
    }
    impl CstDecode<StreamSink<String, flutter_rust_bridge::for_generated::DcoCodec>>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> StreamSink<String, flutter_rust_bridge::for_generated::DcoCodec> {
            StreamSink::deserialize(self.as_string().expect("should be a string"))
        }
    }
    impl CstDecode<String> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self.as_string().expect("non-UTF-8 string, or not a string")
        }
    }
    impl CstDecode<i32> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> i32 {
            self.unchecked_into_f64() as _
        }
    }
    impl CstDecode<Vec<u8>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.unchecked_into::<flutter_rust_bridge::for_generated::js_sys::Uint8Array>()
                .to_vec()
                .into()
        }
    }
    impl CstDecode<crate::api::media::OutputFormat>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::media::OutputFormat {
            (self.unchecked_into_f64() as i32).cst_decode()
        }
    }
    impl CstDecode<u32> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u32 {
            self.unchecked_into_f64() as _
        }
    }
    impl CstDecode<u64> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u64 {
            ::std::convert::TryInto::<u64>::try_into(self).unwrap() as _
        }
    }
    impl CstDecode<u8> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u8 {
            self.unchecked_into_f64() as _
        }
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__media__compress_video(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        path: String,
        output_path: String,
        params: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    ) {
        wire__crate__api__media__compress_video_impl(port_, path, output_path, params)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__media__estimate_compression(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        path: String,
        temp_output_path: String,
        params: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    ) {
        wire__crate__api__media__estimate_compression_impl(port_, path, temp_output_path, params)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__media__generate_image_thumbnail(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        path: String,
        output_path: String,
        params: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    ) {
        wire__crate__api__media__generate_image_thumbnail_impl(port_, path, output_path, params)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__media__generate_video_thumbnail(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        path: String,
        output_path: String,
        params: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    ) {
        wire__crate__api__media__generate_video_thumbnail_impl(port_, path, output_path, params)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__media__generate_video_timeline_thumbnails(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        path: String,
        output_path: String,
        params: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
        num_thumbnails: u32,
        sink: String,
    ) {
        wire__crate__api__media__generate_video_timeline_thumbnails_impl(
            port_,
            path,
            output_path,
            params,
            num_thumbnails,
            sink,
        )
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__media__get_video_info(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        path: String,
    ) {
        wire__crate__api__media__get_video_info_impl(port_, path)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__media__output_format_extension(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        that: i32,
    ) {
        wire__crate__api__media__output_format_extension_impl(port_, that)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__media__thumbnail_size_type_dimensions(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        that: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
    ) {
        wire__crate__api__media__thumbnail_size_type_dimensions_impl(port_, that)
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
