// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<VideoProbe> probeVideo({required String path}) =>
    RustLib.instance.api.crateApiProbeVideo(path: path);

Future<Uint8List> thumbnailImage({
  required String path,
  required double timeSec,
  required int maxEdge,
  required ThumbnailFormat format,
}) => RustLib.instance.api.crateApiThumbnailImage(
  path: path,
  timeSec: timeSec,
  maxEdge: maxEdge,
  format: format,
);

Future<String> thumbnailSaveToPath({
  required String path,
  required String outputPath,
  required double timeSec,
  required int maxEdge,
  required ThumbnailFormat format,
}) => RustLib.instance.api.crateApiThumbnailSaveToPath(
  path: path,
  outputPath: outputPath,
  timeSec: timeSec,
  maxEdge: maxEdge,
  format: format,
);

Stream<TimelineThumbnail> timelineThumbnails({
  required String path,
  required int frameCount,
  required int maxEdge,
  required ThumbnailFormat format,
}) => RustLib.instance.api.crateApiTimelineThumbnails(
  path: path,
  frameCount: frameCount,
  maxEdge: maxEdge,
  format: format,
);

Stream<TranscodeProgress> videoToGif({
  required String inputPath,
  required String outputPath,
  required int fps,
  required int maxEdge,
  double? startSec,
  double? durationSec,
}) => RustLib.instance.api.crateApiVideoToGif(
  inputPath: inputPath,
  outputPath: outputPath,
  fps: fps,
  maxEdge: maxEdge,
  startSec: startSec,
  durationSec: durationSec,
);

Stream<TranscodeProgress> transcodeVideo({
  required String inputPath,
  required String outputPath,
  required int videoBitrateKbps,
  required int maxWidth,
  required int audioBitrateKbps,
}) => RustLib.instance.api.crateApiTranscodeVideo(
  inputPath: inputPath,
  outputPath: outputPath,
  videoBitrateKbps: videoBitrateKbps,
  maxWidth: maxWidth,
  audioBitrateKbps: audioBitrateKbps,
);

/// Thumbnail image encoding for [thumbnail_image] / [thumbnail_save_to_path] / [timeline_thumbnails].
enum ThumbnailFormat { png, jpeg, webp }

class TimelineThumbnail {
  final int index;
  final double timeSec;
  final Uint8List imageBytes;

  const TimelineThumbnail({
    required this.index,
    required this.timeSec,
    required this.imageBytes,
  });

  @override
  int get hashCode => index.hashCode ^ timeSec.hashCode ^ imageBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineThumbnail &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          timeSec == other.timeSec &&
          imageBytes == other.imageBytes;
}

class TranscodeProgress {
  final String phase;
  final double fraction;
  final String? message;

  const TranscodeProgress({
    required this.phase,
    required this.fraction,
    this.message,
  });

  @override
  int get hashCode => phase.hashCode ^ fraction.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscodeProgress &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          fraction == other.fraction &&
          message == other.message;
}

class VideoProbe {
  final PlatformInt64? durationMs;
  final int? width;
  final int? height;
  final PlatformInt64? videoBitrate;
  final PlatformInt64? audioBitrate;
  final double? frameRate;
  final String? videoCodec;
  final String? audioCodec;

  const VideoProbe({
    this.durationMs,
    this.width,
    this.height,
    this.videoBitrate,
    this.audioBitrate,
    this.frameRate,
    this.videoCodec,
    this.audioCodec,
  });

  @override
  int get hashCode =>
      durationMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      videoBitrate.hashCode ^
      audioBitrate.hashCode ^
      frameRate.hashCode ^
      videoCodec.hashCode ^
      audioCodec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoProbe &&
          runtimeType == other.runtimeType &&
          durationMs == other.durationMs &&
          width == other.width &&
          height == other.height &&
          videoBitrate == other.videoBitrate &&
          audioBitrate == other.audioBitrate &&
          frameRate == other.frameRate &&
          videoCodec == other.videoCodec &&
          audioCodec == other.audioCodec;
}
