// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<TimelineThumbnail>
  dco_decode_StreamSink_timeline_thumbnail_Dco(dynamic raw);

  @protected
  RustStreamSink<TranscodeProgress>
  dco_decode_StreamSink_transcode_progress_Dco(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  ThumbnailFormat dco_decode_thumbnail_format(dynamic raw);

  @protected
  TimelineThumbnail dco_decode_timeline_thumbnail(dynamic raw);

  @protected
  TranscodeProgress dco_decode_transcode_progress(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VideoProbe dco_decode_video_probe(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<TimelineThumbnail>
  sse_decode_StreamSink_timeline_thumbnail_Dco(SseDeserializer deserializer);

  @protected
  RustStreamSink<TranscodeProgress>
  sse_decode_StreamSink_transcode_progress_Dco(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ThumbnailFormat sse_decode_thumbnail_format(SseDeserializer deserializer);

  @protected
  TimelineThumbnail sse_decode_timeline_thumbnail(SseDeserializer deserializer);

  @protected
  TranscodeProgress sse_decode_transcode_progress(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VideoProbe sse_decode_video_probe(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
    AnyhowException raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
  cst_encode_StreamSink_timeline_thumbnail_Dco(
    RustStreamSink<TimelineThumbnail> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_timeline_thumbnail,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
  cst_encode_StreamSink_transcode_progress_Dco(
    RustStreamSink<TranscodeProgress> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_transcode_progress,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Double> cst_encode_box_autoadd_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_f_64(cst_encode_f_64(raw));
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_64(cst_encode_i_64(raw));
  }

  @protected
  ffi.Pointer<ffi.Uint32> cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_u_32(cst_encode_u_32(raw));
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Double> cst_encode_opt_box_autoadd_f_64(double? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_f_64(raw);
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  ffi.Pointer<ffi.Uint32> cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  void cst_api_fill_to_wire_timeline_thumbnail(
    TimelineThumbnail apiObj,
    wire_cst_timeline_thumbnail wireObj,
  ) {
    wireObj.index = cst_encode_u_32(apiObj.index);
    wireObj.time_sec = cst_encode_f_64(apiObj.timeSec);
    wireObj.image_bytes = cst_encode_list_prim_u_8_strict(apiObj.imageBytes);
  }

  @protected
  void cst_api_fill_to_wire_transcode_progress(
    TranscodeProgress apiObj,
    wire_cst_transcode_progress wireObj,
  ) {
    wireObj.phase = cst_encode_String(apiObj.phase);
    wireObj.fraction = cst_encode_f_64(apiObj.fraction);
    wireObj.message = cst_encode_opt_String(apiObj.message);
  }

  @protected
  void cst_api_fill_to_wire_video_probe(
    VideoProbe apiObj,
    wire_cst_video_probe wireObj,
  ) {
    wireObj.duration_ms = cst_encode_opt_box_autoadd_i_64(apiObj.durationMs);
    wireObj.width = cst_encode_opt_box_autoadd_u_32(apiObj.width);
    wireObj.height = cst_encode_opt_box_autoadd_u_32(apiObj.height);
    wireObj.video_bitrate = cst_encode_opt_box_autoadd_i_64(
      apiObj.videoBitrate,
    );
    wireObj.audio_bitrate = cst_encode_opt_box_autoadd_i_64(
      apiObj.audioBitrate,
    );
    wireObj.frame_rate = cst_encode_opt_box_autoadd_f_64(apiObj.frameRate);
    wireObj.video_codec = cst_encode_opt_String(apiObj.videoCodec);
    wireObj.audio_codec = cst_encode_opt_String(apiObj.audioCodec);
  }

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_thumbnail_format(ThumbnailFormat raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_timeline_thumbnail_Dco(
    RustStreamSink<TimelineThumbnail> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_transcode_progress_Dco(
    RustStreamSink<TranscodeProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_thumbnail_format(
    ThumbnailFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timeline_thumbnail(
    TimelineThumbnail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcode_progress(
    TranscodeProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_video_probe(VideoProbe self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__probe_video(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
  ) {
    return _wire__crate__api__probe_video(port_, path);
  }

  late final _wire__crate__api__probe_videoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_media_wire__crate__api__probe_video');
  late final _wire__crate__api__probe_video = _wire__crate__api__probe_videoPtr
      .asFunction<
        void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
      >();

  void wire__crate__api__thumbnail_image(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
    double time_sec,
    int max_edge,
    int format,
  ) {
    return _wire__crate__api__thumbnail_image(
      port_,
      path,
      time_sec,
      max_edge,
      format,
    );
  }

  late final _wire__crate__api__thumbnail_imagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Double,
            ffi.Uint32,
            ffi.Int32,
          )
        >
      >('frbgen_media_wire__crate__api__thumbnail_image');
  late final _wire__crate__api__thumbnail_image =
      _wire__crate__api__thumbnail_imagePtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              double,
              int,
              int,
            )
          >();

  void wire__crate__api__thumbnail_save_to_path(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> output_path,
    double time_sec,
    int max_edge,
    int format,
  ) {
    return _wire__crate__api__thumbnail_save_to_path(
      port_,
      path,
      output_path,
      time_sec,
      max_edge,
      format,
    );
  }

  late final _wire__crate__api__thumbnail_save_to_pathPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Double,
            ffi.Uint32,
            ffi.Int32,
          )
        >
      >('frbgen_media_wire__crate__api__thumbnail_save_to_path');
  late final _wire__crate__api__thumbnail_save_to_path =
      _wire__crate__api__thumbnail_save_to_pathPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              double,
              int,
              int,
            )
          >();

  void wire__crate__api__timeline_thumbnails(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> path,
    int frame_count,
    int max_edge,
    int format,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> sink,
  ) {
    return _wire__crate__api__timeline_thumbnails(
      port_,
      path,
      frame_count,
      max_edge,
      format,
      sink,
    );
  }

  late final _wire__crate__api__timeline_thumbnailsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Int32,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_media_wire__crate__api__timeline_thumbnails');
  late final _wire__crate__api__timeline_thumbnails =
      _wire__crate__api__timeline_thumbnailsPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  void wire__crate__api__transcode_video(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> input_path,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> output_path,
    int video_bitrate_kbps,
    int max_width,
    int audio_bitrate_kbps,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> sink,
  ) {
    return _wire__crate__api__transcode_video(
      port_,
      input_path,
      output_path,
      video_bitrate_kbps,
      max_width,
      audio_bitrate_kbps,
      sink,
    );
  }

  late final _wire__crate__api__transcode_videoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_media_wire__crate__api__transcode_video');
  late final _wire__crate__api__transcode_video =
      _wire__crate__api__transcode_videoPtr
          .asFunction<
            void Function(
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
              int,
              int,
              int,
              ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            )
          >();

  ffi.Pointer<ffi.Double> cst_new_box_autoadd_f_64(double value) {
    return _cst_new_box_autoadd_f_64(value);
  }

  late final _cst_new_box_autoadd_f_64Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Double> Function(ffi.Double)>>(
        'frbgen_media_cst_new_box_autoadd_f_64',
      );
  late final _cst_new_box_autoadd_f_64 = _cst_new_box_autoadd_f_64Ptr
      .asFunction<ffi.Pointer<ffi.Double> Function(double)>();

  ffi.Pointer<ffi.Int64> cst_new_box_autoadd_i_64(int value) {
    return _cst_new_box_autoadd_i_64(value);
  }

  late final _cst_new_box_autoadd_i_64Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int64> Function(ffi.Int64)>>(
        'frbgen_media_cst_new_box_autoadd_i_64',
      );
  late final _cst_new_box_autoadd_i_64 = _cst_new_box_autoadd_i_64Ptr
      .asFunction<ffi.Pointer<ffi.Int64> Function(int)>();

  ffi.Pointer<ffi.Uint32> cst_new_box_autoadd_u_32(int value) {
    return _cst_new_box_autoadd_u_32(value);
  }

  late final _cst_new_box_autoadd_u_32Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Uint32> Function(ffi.Uint32)>>(
        'frbgen_media_cst_new_box_autoadd_u_32',
      );
  late final _cst_new_box_autoadd_u_32 = _cst_new_box_autoadd_u_32Ptr
      .asFunction<ffi.Pointer<ffi.Uint32> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_media_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_timeline_thumbnail extends ffi.Struct {
  @ffi.Uint32()
  external int index;

  @ffi.Double()
  external double time_sec;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> image_bytes;
}

final class wire_cst_transcode_progress extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> phase;

  @ffi.Double()
  external double fraction;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> message;
}

final class wire_cst_video_probe extends ffi.Struct {
  external ffi.Pointer<ffi.Int64> duration_ms;

  external ffi.Pointer<ffi.Uint32> width;

  external ffi.Pointer<ffi.Uint32> height;

  external ffi.Pointer<ffi.Int64> video_bitrate;

  external ffi.Pointer<ffi.Int64> audio_bitrate;

  external ffi.Pointer<ffi.Double> frame_rate;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> video_codec;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> audio_codec;
}
