// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<TimelineThumbnail>
  dco_decode_StreamSink_timeline_thumbnail_Dco(dynamic raw);

  @protected
  RustStreamSink<TranscodeProgress>
  dco_decode_StreamSink_transcode_progress_Dco(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  ThumbnailFormat dco_decode_thumbnail_format(dynamic raw);

  @protected
  TimelineThumbnail dco_decode_timeline_thumbnail(dynamic raw);

  @protected
  TranscodeProgress dco_decode_transcode_progress(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VideoProbe dco_decode_video_probe(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<TimelineThumbnail>
  sse_decode_StreamSink_timeline_thumbnail_Dco(SseDeserializer deserializer);

  @protected
  RustStreamSink<TranscodeProgress>
  sse_decode_StreamSink_transcode_progress_Dco(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ThumbnailFormat sse_decode_thumbnail_format(SseDeserializer deserializer);

  @protected
  TimelineThumbnail sse_decode_timeline_thumbnail(SseDeserializer deserializer);

  @protected
  TranscodeProgress sse_decode_transcode_progress(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VideoProbe sse_decode_video_probe(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String cst_encode_StreamSink_timeline_thumbnail_Dco(
    RustStreamSink<TimelineThumbnail> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_timeline_thumbnail,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  String cst_encode_StreamSink_transcode_progress_Dco(
    RustStreamSink<TranscodeProgress> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_transcode_progress,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  double cst_encode_box_autoadd_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_f_64(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_64(raw);
  }

  @protected
  int cst_encode_box_autoadd_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_32(raw);
  }

  @protected
  JSAny cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  double? cst_encode_opt_box_autoadd_f_64(double? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_f_64(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_u_32(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_32(raw);
  }

  @protected
  JSAny cst_encode_timeline_thumbnail(TimelineThumbnail raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_u_32(raw.index),
      cst_encode_f_64(raw.timeSec),
      cst_encode_list_prim_u_8_strict(raw.imageBytes),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_transcode_progress(TranscodeProgress raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.phase),
      cst_encode_f_64(raw.fraction),
      cst_encode_opt_String(raw.message),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_video_probe(VideoProbe raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_box_autoadd_i_64(raw.durationMs),
      cst_encode_opt_box_autoadd_u_32(raw.width),
      cst_encode_opt_box_autoadd_u_32(raw.height),
      cst_encode_opt_box_autoadd_i_64(raw.videoBitrate),
      cst_encode_opt_box_autoadd_i_64(raw.audioBitrate),
      cst_encode_opt_box_autoadd_f_64(raw.frameRate),
      cst_encode_opt_String(raw.videoCodec),
      cst_encode_opt_String(raw.audioCodec),
    ].jsify()!;
  }

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_thumbnail_format(ThumbnailFormat raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_timeline_thumbnail_Dco(
    RustStreamSink<TimelineThumbnail> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_transcode_progress_Dco(
    RustStreamSink<TranscodeProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_thumbnail_format(
    ThumbnailFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_timeline_thumbnail(
    TimelineThumbnail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcode_progress(
    TranscodeProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_video_probe(VideoProbe self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__probe_video(NativePortType port_, String path) =>
      wasmModule.wire__crate__api__probe_video(port_, path);

  void wire__crate__api__thumbnail_image(
    NativePortType port_,
    String path,
    double time_sec,
    int max_edge,
    int format,
  ) => wasmModule.wire__crate__api__thumbnail_image(
    port_,
    path,
    time_sec,
    max_edge,
    format,
  );

  void wire__crate__api__thumbnail_save_to_path(
    NativePortType port_,
    String path,
    String output_path,
    double time_sec,
    int max_edge,
    int format,
  ) => wasmModule.wire__crate__api__thumbnail_save_to_path(
    port_,
    path,
    output_path,
    time_sec,
    max_edge,
    format,
  );

  void wire__crate__api__timeline_thumbnails(
    NativePortType port_,
    String path,
    int frame_count,
    int max_edge,
    int format,
    String sink,
  ) => wasmModule.wire__crate__api__timeline_thumbnails(
    port_,
    path,
    frame_count,
    max_edge,
    format,
    sink,
  );

  void wire__crate__api__transcode_video(
    NativePortType port_,
    String input_path,
    String output_path,
    int video_bitrate_kbps,
    int max_width,
    int audio_bitrate_kbps,
    String sink,
  ) => wasmModule.wire__crate__api__transcode_video(
    port_,
    input_path,
    output_path,
    video_bitrate_kbps,
    max_width,
    audio_bitrate_kbps,
    sink,
  );

  void wire__crate__api__video_to_gif(
    NativePortType port_,
    String input_path,
    String output_path,
    int fps,
    int max_edge,
    double? start_sec,
    double? duration_sec,
    String sink,
  ) => wasmModule.wire__crate__api__video_to_gif(
    port_,
    input_path,
    output_path,
    fps,
    max_edge,
    start_sec,
    duration_sec,
    sink,
  );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__probe_video(
    NativePortType port_,
    String path,
  );

  external void wire__crate__api__thumbnail_image(
    NativePortType port_,
    String path,
    double time_sec,
    int max_edge,
    int format,
  );

  external void wire__crate__api__thumbnail_save_to_path(
    NativePortType port_,
    String path,
    String output_path,
    double time_sec,
    int max_edge,
    int format,
  );

  external void wire__crate__api__timeline_thumbnails(
    NativePortType port_,
    String path,
    int frame_count,
    int max_edge,
    int format,
    String sink,
  );

  external void wire__crate__api__transcode_video(
    NativePortType port_,
    String input_path,
    String output_path,
    int video_bitrate_kbps,
    int max_width,
    int audio_bitrate_kbps,
    String sink,
  );

  external void wire__crate__api__video_to_gif(
    NativePortType port_,
    String input_path,
    String output_path,
    int fps,
    int max_edge,
    double? start_sec,
    double? duration_sec,
    String sink,
  );
}
