// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 793834831;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'media',
        ioDirectory: 'rust/media/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<VideoProbe> crateApiProbeVideo({required String path});

  Future<Uint8List> crateApiThumbnailImage({
    required String path,
    required double timeSec,
    required int maxEdge,
    required ThumbnailFormat format,
  });

  Future<String> crateApiThumbnailSaveToPath({
    required String path,
    required String outputPath,
    required double timeSec,
    required int maxEdge,
    required ThumbnailFormat format,
  });

  Stream<TimelineThumbnail> crateApiTimelineThumbnails({
    required String path,
    required int frameCount,
    required int maxEdge,
    required ThumbnailFormat format,
  });

  Stream<TranscodeProgress> crateApiTranscodeVideo({
    required String inputPath,
    required String outputPath,
    required int videoBitrateKbps,
    required int maxWidth,
    required int audioBitrateKbps,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<VideoProbe> crateApiProbeVideo({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(path);
          return wire.wire__crate__api__probe_video(port_, arg0);
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_video_probe,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiProbeVideoConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProbeVideoConstMeta =>
      const TaskConstMeta(debugName: "probe_video", argNames: ["path"]);

  @override
  Future<Uint8List> crateApiThumbnailImage({
    required String path,
    required double timeSec,
    required int maxEdge,
    required ThumbnailFormat format,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(path);
          var arg1 = cst_encode_f_64(timeSec);
          var arg2 = cst_encode_u_32(maxEdge);
          var arg3 = cst_encode_thumbnail_format(format);
          return wire.wire__crate__api__thumbnail_image(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_list_prim_u_8_strict,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiThumbnailImageConstMeta,
        argValues: [path, timeSec, maxEdge, format],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiThumbnailImageConstMeta => const TaskConstMeta(
    debugName: "thumbnail_image",
    argNames: ["path", "timeSec", "maxEdge", "format"],
  );

  @override
  Future<String> crateApiThumbnailSaveToPath({
    required String path,
    required String outputPath,
    required double timeSec,
    required int maxEdge,
    required ThumbnailFormat format,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          var arg0 = cst_encode_String(path);
          var arg1 = cst_encode_String(outputPath);
          var arg2 = cst_encode_f_64(timeSec);
          var arg3 = cst_encode_u_32(maxEdge);
          var arg4 = cst_encode_thumbnail_format(format);
          return wire.wire__crate__api__thumbnail_save_to_path(
            port_,
            arg0,
            arg1,
            arg2,
            arg3,
            arg4,
          );
        },
        codec: DcoCodec(
          decodeSuccessData: dco_decode_String,
          decodeErrorData: dco_decode_String,
        ),
        constMeta: kCrateApiThumbnailSaveToPathConstMeta,
        argValues: [path, outputPath, timeSec, maxEdge, format],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiThumbnailSaveToPathConstMeta =>
      const TaskConstMeta(
        debugName: "thumbnail_save_to_path",
        argNames: ["path", "outputPath", "timeSec", "maxEdge", "format"],
      );

  @override
  Stream<TimelineThumbnail> crateApiTimelineThumbnails({
    required String path,
    required int frameCount,
    required int maxEdge,
    required ThumbnailFormat format,
  }) {
    final sink = RustStreamSink<TimelineThumbnail>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            var arg0 = cst_encode_String(path);
            var arg1 = cst_encode_u_32(frameCount);
            var arg2 = cst_encode_u_32(maxEdge);
            var arg3 = cst_encode_thumbnail_format(format);
            var arg4 = cst_encode_StreamSink_timeline_thumbnail_Dco(sink);
            return wire.wire__crate__api__timeline_thumbnails(
              port_,
              arg0,
              arg1,
              arg2,
              arg3,
              arg4,
            );
          },
          codec: DcoCodec(
            decodeSuccessData: dco_decode_unit,
            decodeErrorData: dco_decode_String,
          ),
          constMeta: kCrateApiTimelineThumbnailsConstMeta,
          argValues: [path, frameCount, maxEdge, format, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTimelineThumbnailsConstMeta => const TaskConstMeta(
    debugName: "timeline_thumbnails",
    argNames: ["path", "frameCount", "maxEdge", "format", "sink"],
  );

  @override
  Stream<TranscodeProgress> crateApiTranscodeVideo({
    required String inputPath,
    required String outputPath,
    required int videoBitrateKbps,
    required int maxWidth,
    required int audioBitrateKbps,
  }) {
    final sink = RustStreamSink<TranscodeProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            var arg0 = cst_encode_String(inputPath);
            var arg1 = cst_encode_String(outputPath);
            var arg2 = cst_encode_u_32(videoBitrateKbps);
            var arg3 = cst_encode_u_32(maxWidth);
            var arg4 = cst_encode_u_32(audioBitrateKbps);
            var arg5 = cst_encode_StreamSink_transcode_progress_Dco(sink);
            return wire.wire__crate__api__transcode_video(
              port_,
              arg0,
              arg1,
              arg2,
              arg3,
              arg4,
              arg5,
            );
          },
          codec: DcoCodec(
            decodeSuccessData: dco_decode_unit,
            decodeErrorData: dco_decode_String,
          ),
          constMeta: kCrateApiTranscodeVideoConstMeta,
          argValues: [
            inputPath,
            outputPath,
            videoBitrateKbps,
            maxWidth,
            audioBitrateKbps,
            sink,
          ],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiTranscodeVideoConstMeta => const TaskConstMeta(
    debugName: "transcode_video",
    argNames: [
      "inputPath",
      "outputPath",
      "videoBitrateKbps",
      "maxWidth",
      "audioBitrateKbps",
      "sink",
    ],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<TimelineThumbnail>
  dco_decode_StreamSink_timeline_thumbnail_Dco(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<TranscodeProgress>
  dco_decode_StreamSink_transcode_progress_Dco(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  ThumbnailFormat dco_decode_thumbnail_format(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ThumbnailFormat.values[raw as int];
  }

  @protected
  TimelineThumbnail dco_decode_timeline_thumbnail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TimelineThumbnail(
      index: dco_decode_u_32(arr[0]),
      timeSec: dco_decode_f_64(arr[1]),
      imageBytes: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  TranscodeProgress dco_decode_transcode_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TranscodeProgress(
      phase: dco_decode_String(arr[0]),
      fraction: dco_decode_f_64(arr[1]),
      message: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VideoProbe dco_decode_video_probe(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return VideoProbe(
      durationMs: dco_decode_opt_box_autoadd_i_64(arr[0]),
      width: dco_decode_opt_box_autoadd_u_32(arr[1]),
      height: dco_decode_opt_box_autoadd_u_32(arr[2]),
      videoBitrate: dco_decode_opt_box_autoadd_i_64(arr[3]),
      audioBitrate: dco_decode_opt_box_autoadd_i_64(arr[4]),
      frameRate: dco_decode_opt_box_autoadd_f_64(arr[5]),
      videoCodec: dco_decode_opt_String(arr[6]),
      audioCodec: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<TimelineThumbnail>
  sse_decode_StreamSink_timeline_thumbnail_Dco(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<TranscodeProgress>
  sse_decode_StreamSink_transcode_progress_Dco(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ThumbnailFormat sse_decode_thumbnail_format(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ThumbnailFormat.values[inner];
  }

  @protected
  TimelineThumbnail sse_decode_timeline_thumbnail(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_timeSec = sse_decode_f_64(deserializer);
    var var_imageBytes = sse_decode_list_prim_u_8_strict(deserializer);
    return TimelineThumbnail(
      index: var_index,
      timeSec: var_timeSec,
      imageBytes: var_imageBytes,
    );
  }

  @protected
  TranscodeProgress sse_decode_transcode_progress(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_String(deserializer);
    var var_fraction = sse_decode_f_64(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    return TranscodeProgress(
      phase: var_phase,
      fraction: var_fraction,
      message: var_message,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VideoProbe sse_decode_video_probe(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_durationMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_videoBitrate = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_audioBitrate = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_frameRate = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_videoCodec = sse_decode_opt_String(deserializer);
    var var_audioCodec = sse_decode_opt_String(deserializer);
    return VideoProbe(
      durationMs: var_durationMs,
      width: var_width,
      height: var_height,
      videoBitrate: var_videoBitrate,
      audioBitrate: var_audioBitrate,
      frameRate: var_frameRate,
      videoCodec: var_videoCodec,
      audioCodec: var_audioCodec,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double cst_encode_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_thumbnail_format(ThumbnailFormat raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_timeline_thumbnail_Dco(
    RustStreamSink<TimelineThumbnail> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_timeline_thumbnail,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_transcode_progress_Dco(
    RustStreamSink<TranscodeProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_transcode_progress,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_thumbnail_format(
    ThumbnailFormat self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_timeline_thumbnail(
    TimelineThumbnail self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_f_64(self.timeSec, serializer);
    sse_encode_list_prim_u_8_strict(self.imageBytes, serializer);
  }

  @protected
  void sse_encode_transcode_progress(
    TranscodeProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.phase, serializer);
    sse_encode_f_64(self.fraction, serializer);
    sse_encode_opt_String(self.message, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_video_probe(VideoProbe self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.durationMs, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_opt_box_autoadd_i_64(self.videoBitrate, serializer);
    sse_encode_opt_box_autoadd_i_64(self.audioBitrate, serializer);
    sse_encode_opt_box_autoadd_f_64(self.frameRate, serializer);
    sse_encode_opt_String(self.videoCodec, serializer);
    sse_encode_opt_String(self.audioCodec, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
